# Generated by Django 4.1.5 on 2023-01-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_eingine_car_engine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="car",
        ),
        migrations.AddField(
            model_name="part",
            name="cars",
            field=models.ManyToManyField(blank=True, to="shop.car"),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.CharField(max_length=10),
        ),
    ]
