# Generated by Django 4.1.5 on 2023-01-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_part_car_part_cars_alter_car_engine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="category",
            field=models.CharField(
                choices=[
                    ("BRAKES", "BRAKES"),
                    ("WINDOW", "WINDOW"),
                    ("GEARBOX", "GEARBOX"),
                    ("DOOR", "DOOR"),
                    ("OTHER", "OTHER"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="image_filename",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="image_url",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
