# Generated by Django 4.1.5 on 2023-01-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_part_category_part_image_filename_part_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="image_filename",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="part",
            name="image_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
