# Generated by Django 4.1.5 on 2023-01-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_part_image_filename_alter_part_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="name",
            field=models.CharField(default="Brakes", max_length=100),
            preserve_default=False,
        ),
    ]
