# Generated by Django 4.1.5 on 2023-01-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_part_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="inventory",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
