# Generated by Django 4.1.5 on 2023-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_part_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
