# Generated by Django 4.1.5 on 2023-01-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_mpesatransaction_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpesatransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
