# Generated by Django 4.1.5 on 2023-02-08 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_pesapaltransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesapaltransaction",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
