# Generated by Django 4.1.5 on 2023-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_pesapaltransaction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="brand",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="description",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
