# Generated by Django 4.1.7 on 2023-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_uservehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="image_url",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
